# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pip install pyinstaller
          pip install -r requirements.txt
          pyinstaller -D -w --add-data 'data\*;data'`
          --add-data 'levels\*;levels'`
          --add-data 'sprites\*.*;sprites'`
          --add-data 'sprites\character_forward\*;sprites\character_forward'`
          --add-data 'sprites\character_static\*;sprites\character_static'`
          --add-data 'sprites\goblin_attacking\*;sprites\goblin_attacking'`
          --add-data 'sprites\goblin_walking\*;sprites\goblin_walking'`
          --add-data 'sprites\start_screen\*;sprites\start_screen'`
          --add-data 'sprites\sword_attacking\*;sprites\sword_attacking'`
          --add-data 'sprites\torch_animation\*;sprites\torch_animation'`
          main.py
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: main
          path: dist\
          retention-days: 5
